site_name: WasmEdge Mentorship
site_url: https://hydai.github.io/mentorship
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
